### ISSUE TITLE
Still some java.lang.ArrayIndexOutOfBoundsException in last dev

### ISSUE THREAD

**Issue by Tolriq** [SimonVT/android-menudrawer#125]
Hi,

I still get some random crash reported by users :

```
STACK_TRACE=java.lang.ArrayIndexOutOfBoundsException
at android.view.MotionEvent.getX(MotionEvent.java:972)
at net.simonvt.menudrawer.i.b(SourceFile:205)
at net.simonvt.menudrawer.h.onTouchEvent(SourceFile:236)
at android.view.View.dispatchTouchEvent(View.java:3932)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:955)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1236)
at android.view.ViewRoot.dispatchDetachedFromWindow(ViewRoot.java:1834)
at android.view.ViewRoot.doDie(ViewRoot.java:2899)
at android.view.ViewRoot.die(ViewRoot.java:2869)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:254)
at android.view.Window$LocalWindowManager.removeViewImmediate(Window.java:445)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3166)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3271)
at android.app.ActivityThread.access$1600(ActivityThread.java:132)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1042)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:4277)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
```

But only very few and none of the users where able to explain me what they did to trigger this :(

Got this on
ANDROID_VERSION=4.2.2
BRAND=google
PHONE_MODEL=Nexus 7

to

ANDROID_VERSION=2.3.5
BRAND=vodafone_uk
PHONE_MODEL=HTC Wildfire S A510e

So does not seems related to Android version.

**Comment by felixb** [comment]
I've a MapView (v3) inside the content view. When scrolling around, I get these random crashes too.
I'm running the master branch and getting a java.lang.IllegalArgumentException with similar stack trace.

Running on N4 with Android 4.2.2.

```
java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:1981)
        at net.simonvt.menudrawer.HorizontalDrawer.onInterceptTouchEvent(HorizontalDrawer.java:107)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1817)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2211)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1458)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2159)
        at android.view.View.dispatchPointerEvent(View.java:7426)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3220)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3165)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4342)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4382)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
        at android.view.Choreographer.doCallbacks(Choreographer.java:562)
        at android.view.Choreographer.doFrame(Choreographer.java:530)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5226)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by felixb** [comment]
Ok, my bad. It had nothing to do with the MapView, but it's fixed in dev anyway.

**Comment by Tolriq** [comment]
I first was thinking my users report where wrong but I get more on more users commenting on this crash that they where not even using the app when the crash occurs.

Don't know if this can help understand better the cases.

**Comment by SimonVT** [comment]
What do you mean they're not using your app?

**Comment by Tolriq** [comment]
From the comments the app was not in the foreground i guess they returned to home or switched to another app.

Sounds weird but since I already get at least 10 crash from different users with the same kind of comment I had to mention it.

Still on 3.0.1 in prod

**Comment by SimonVT** [comment]
I get touch events when the app isn't in the foreground? That sounds more like a broken framework. But I guess I have to handle it.
I pushed a commit to the dev branch that attempts to resolve this, but I hate these workaround because it's not clear if it hides broken behavior in my implementation. For now I'll just have to assume this is not something the user is likely to encounter during normal interaction.

**Comment by Tolriq** [comment]
Well this happens on 2.x and 4.0.x, 4.2.2 and multiple brands.

I'll update my beta build with this and see the result.
Anyway thanks for the fix.
