### ISSUE TITLE
need ActionBarHelperCompat

### ISSUE THREAD

**Issue by tomykho** [SimonVT/android-menudrawer#171]
Hello, can you add new compatibility for android-support-v7-appcompat library from Google?

**Comment by SimonVT** [comment]
Please try the appcompat branch and tell me if it works.

**Comment by tomykho** [comment]
Still got this error message

```
08-06 11:43:16.392    3108-3108/com.claudkho.mangafox E/ActionBarHelper: Activity MainActivity does not use a compatibility ActionBar
        java.lang.NoSuchMethodException: getSupportActionBar
        at java.lang.ClassCache.findMethodByName(ClassCache.java:247)
        at java.lang.Class.getMethod(Class.java:962)
```

**Comment by SimonVT** [comment]
Added and released.

**Comment by abeatte** [comment]
Is there a sample for how to set this up with appcompat? I am getitng weird behavior with older devices.
