### ISSUE TITLE
java.lang.StackOverflowError at android.text.TextUtils.getChars(TextUtils.java:64)

### ISSUE THREAD

**Issue by kongsonida** [SimonVT/android-menudrawer#204]
I got error like bellow when I integrated this library. It happened for some devices, not all.

java.lang.StackOverflowError
        at android.text.TextUtils.getChars(TextUtils.java:64)
        at android.text.TextUtils$Reverser.getChars(TextUtils.java:515)
        at android.text.TextUtils.getChars(TextUtils.java:70)
        at android.graphics.Paint.measureText(Paint.java:1071)
        at android.text.Styled.drawDirectionalRun(Styled.java:260)
        at android.text.Styled.drawText(Styled.java:350)
        at android.text.Layout.drawText(Layout.java:1876)
        at android.text.Layout.draw(Layout.java:703)
        at android.widget.TextView.onDraw(TextView.java:4203)
        at android.view.View.draw(View.java:6944)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1913)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1913)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.draw(View.java:6947)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.buildDrawingCache(View.java:6665)
        at android.view.View.getDrawingCache(View.java:6453)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1840)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.widget.AbsListView.dispatchDraw(AbsListView.java:1407)
        at android.widget.ListView.dispatchDraw(ListView.java:3052)
        at android.view.View.draw(View.java:7056)
        at android.widget.AbsListView.draw(AbsListView.java:2303)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.draw(View.java:6947)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1913)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.draw(View.java:6947)
        at android.support.v4.view.ViewPager.draw(ViewPager.java:2171)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.draw(View.java:6947)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1913)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.draw(View.java:6947)
        at android.widget.FrameLayout.draw(FrameLayout.java:352)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.draw(View.java:6947)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at net.simonvt.menudrawer.BuildLayerFrameLayout.dispatchDraw(BuildLayerFrameLayout.java:77)
        at android.view.View.draw(View.java:6947)
        at android.widget.FrameLayout.draw(FrameLayout.java:352)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at net.simonvt.menudrawer.MenuDrawer.dispatchDraw(MenuDrawer.java:679)
        at android.view.View.draw(View.java:6947)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1915)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1913)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1913)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1913)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1642)
        at android.view.View.draw(View.java:6947)
        at android.widget.FrameLayout.draw(FrameLayout.java:352)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1911)
        at android.view.ViewRoot.draw(ViewRoot.java:1422)
        at android.view.ViewRoot.performTraversals(ViewRoot.java:1167)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1748)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:143)
        at android.app.ActivityThread.main(ActivityThread.java:5073)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
I only add two levels to the view hierarchy, which really isn't a lot. I can't do anything in the library to solve this.

**Comment by mykola-dev** [comment]
Have similar issue. Only on Amazon devices

java.lang.StackOverflowError
       at android.view.GLES20RecordingCanvas.<init>(GLES20RecordingCanvas.java:63)
       at android.view.GLES20RecordingCanvas.<init>(GLES20RecordingCanvas.java:39)
       at android.view.GLES20RecordingCanvas$1.newInstance(GLES20RecordingCanvas.java:47)
       at android.view.GLES20RecordingCanvas$1.newInstance(GLES20RecordingCanvas.java:45)
       at android.util.FinitePool.acquire(FinitePool.java:69)
       at android.util.SynchronizedPool.acquire(SynchronizedPool.java:39)
       at android.view.GLES20RecordingCanvas.obtain(GLES20RecordingCanvas.java:67)
       at android.view.GLES20DisplayList.start(GLES20DisplayList.java:52)
       at android.view.View.getDisplayList(View.java:10425)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11010)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.widget.ListView.drawChild(ListView.java:3223)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.widget.AbsListView.dispatchDraw(AbsListView.java:2102)
       at android.widget.ListView.dispatchDraw(ListView.java:3218)
       at android.view.View.draw(View.java:11010)
       at android.widget.AbsListView.draw(AbsListView.java:3426)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11010)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11010)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.widget.ScrollView.draw(ScrollView.java:1524)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11010)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at net.simonvt.menudrawer.BuildLayerFrameLayout.dispatchDraw(BuildLayerFrameLayout.java:77)
       at android.view.View.draw(View.java:11010)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at net.simonvt.menudrawer.MenuDrawer.dispatchDraw(MenuDrawer.java:671)
       at android.view.View.draw(View.java:11010)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:870)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at net.simonvt.menudrawer.BuildLayerFrameLayout.dispatchDraw(BuildLayerFrameLayout.java:77)
       at android.view.View.draw(View.java:11010)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at net.simonvt.menudrawer.MenuDrawer.dispatchDraw(MenuDrawer.java:671)
       at android.view.View.draw(View.java:11010)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11010)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.getDisplayList(View.java:10444)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
       at android.view.View.draw(View.java:11010)
       at android.widget.FrameLayout.draw(FrameLayout.java:450)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2302)
       at android.view.View.getDisplayList(View.java:10446)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:842)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:1924)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1647)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2462)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4533)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
