### ISSUE TITLE
Use a fragment as a menu view?

### ISSUE THREAD

**Issue by andy61i** [SimonVT/android-menudrawer#45]
I am trying to use a fragment (inside a `FrameLayout`) for `setMenuView()`, but it crashes on Android 4.1. Any suggestion how to fix/workaround that?

Here is the code:

``` java
@Override
public void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  mMenuDrawerManager = new MenuDrawerManager(this, MenuDrawer.MENU_DRAG_WINDOW);
  mMenuDrawerManager.setContentView(R.layout.card_list_activity);
  mMenuDrawerManager.setMenuView(R.layout.card_list_menu); // this line causes the crash
}
```

And the error:

```
12-05 17:25:12.615: E/AndroidRuntime(30997): android.view.InflateException: Binary XML file line #17: Error inflating class
```

**Comment by JakeWharton** [comment]
Paste the entire stack trace.

**Comment by andy61i** [comment]
```
12-05 17:25:12.585: W/ResourceType(30997): Failure getting entry for 0x7f0a001d (t=9 e=29) in package 0 (error -75)
12-05 17:25:12.585: W/dalvikvm(30997): threadid=1: thread exiting with uncaught exception (group=0x414342a0)
12-05 17:25:12.615: E/AndroidRuntime(30997): FATAL EXCEPTION: main
12-05 17:25:12.615: E/AndroidRuntime(30997): android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at com.safeincloud.LabelPanelAdapter.getView(LabelPanelAdapter.java:45)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.AbsListView.obtainView(AbsListView.java:2461)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.ListView.onMeasure(ListView.java:1134)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.View.measure(View.java:15481)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.View.measure(View.java:15481)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1020)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:576)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.View.measure(View.java:15481)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.View.measure(View.java:15481)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.View.measure(View.java:15481)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at net.simonvt.widget.MenuDrawer.onMeasure(MenuDrawer.java:854)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.View.measure(View.java:15481)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5055)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2355)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.View.measure(View.java:15481)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1976)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1219)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1392)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1112)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4518)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.Choreographer.doFrame(Choreographer.java:525)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.os.Handler.handleCallback(Handler.java:615)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.os.Handler.dispatchMessage(Handler.java:92)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.os.Looper.loop(Looper.java:137)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.app.ActivityThread.main(ActivityThread.java:4898)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at java.lang.reflect.Method.invokeNative(Native Method)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at java.lang.reflect.Method.invoke(Method.java:511)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at dalvik.system.NativeStart.main(Native Method)
12-05 17:25:12.615: E/AndroidRuntime(30997): Caused by: java.lang.reflect.InvocationTargetException
12-05 17:25:12.615: E/AndroidRuntime(30997):    at java.lang.reflect.Constructor.constructNative(Native Method)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
12-05 17:25:12.615: E/AndroidRuntime(30997):    ... 46 more
12-05 17:25:12.615: E/AndroidRuntime(30997): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.TextView.<init>(TextView.java:911)
12-05 17:25:12.615: E/AndroidRuntime(30997):    at android.widget.TextView.<init>(TextView.java:569)
12-05 17:25:12.615: E/AndroidRuntime(30997):    ... 49 more
```

**Comment by JakeWharton** [comment]
Can you provide the layout you are using? The specific error is here:

```
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
```

Which usually indicates you are using an inappropriate value for `layout_width` or `layout_height`.

**Comment by andy61i** [comment]
I found the problem and it is not connected with MenuDrawer or fragments. In short, one of dimension constants was not declared for a phone layout that I tested. This happened because a fragment I used for a menu view was originally used only for a tablet layout.

Sorry for bothering you and thanks for your help. You can delete this entire issue.

**Comment by ghost** [comment]
Would you care to show the working code snippet? The code and a FrameLayout as you described above does not do the trick.
