### ISSUE TITLE
Error Running on Android 2.1

### ISSUE THREAD

**Issue by donalglov** [SimonVT/android-menudrawer#54]
Hello, whenever I try to attach a side menu on android 2.1(be it on the samples or in my own app) I get an ERROR/AndroidRuntime(4470): FATAL EXCEPTION: main
        java.lang.NoSuchMethodError: net.simonvt.widget.BuildLayerFrameLayout.setLayerType

even when I dont set the layertype.On ICS everything works fine(I am using the dev branch).What can be wrong?

**Comment by SimonVT** [comment]
Please post the full stack trace.

**Comment by donalglov** [comment]
This is the last one,when running content sample

01-04 22:52:22.529: ERROR/AndroidRuntime(4470): FATAL EXCEPTION: main
        java.lang.NoSuchMethodError: net.simonvt.widget.BuildLayerFrameLayout.setLayerType
        at net.simonvt.widget.BuildLayerFrameLayout.<init>(BuildLayerFrameLayout.java:25)
        at net.simonvt.widget.MenuDrawer.<init>(MenuDrawer.java:559)
        at net.simonvt.widget.MenuDrawer.<init>(MenuDrawer.java:511)
        at net.simonvt.widget.MenuDrawer.<init>(MenuDrawer.java:507)
        at net.simonvt.widget.MenuDrawer.<init>(MenuDrawer.java:500)
        at net.simonvt.widget.LeftDrawer.<init>(LeftDrawer.java:15)
        at net.simonvt.widget.MenuDrawer.createMenuDrawer(MenuDrawer.java:461)
        at net.simonvt.widget.MenuDrawer.attach(MenuDrawer.java:437)
        at net.simonvt.widget.MenuDrawer.attach(MenuDrawer.java:423)
        at net.simonvt.menudrawer.samples.ContentSample.onCreate(ContentSample.java:42)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
        at android.app.ActivityThread.access$1500(ActivityThread.java:123)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3839)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
        at dalvik.system.NativeStart.main(Native Method)
01-04 22:52:52.779: ERROR/InputDispatcher(179): channel '40c43ae8 net.simonvt.menudrawer.samples/net.simonvt.menudrawer.samples.SamplesActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x8
01-04 22:52:52.779: ERROR/InputDispatcher(179): channel '40c43ae8 net.simonvt.menudrawer.samples/net.simonvt.menudrawer.samples.SamplesActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by SimonVT** [comment]
I think you need to pull the latest changes.
