### ISSUE TITLE
Orientation change crash when using static menu drawer on one orientation only

### ISSUE THREAD

**Issue by niqo01** [SimonVT/android-menudrawer#62]
Hello, @SimonVT, Thanks for this version 2.0.0.

I am having an issue using MenuDrawer.attach() with attachStatic = true in landscape and attachStatic = false in portrait.

```
mMenuDrawer = MenuDrawer.attach(this, MenuDrawer.MENU_DRAG_CONTENT, Position.LEFT, getResources().getBoolean(R.bool.has_static_menu_drawer));
```

When switching from landscape to portrait I get the exception:

```
Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class net.simonvt.menudrawer.DraggableDrawer$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/md__drawer. Make sure other views do not use the same id.
at android.view.View.onRestoreInstanceState(View.java:12112)
at android.view.View.dispatchRestoreInstanceState(View.java:12088)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2582)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2588)
at android.view.View.restoreHierarchyState(View.java:12066)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1634)
at android.app.Activity.onRestoreInstanceState(Activity.java:938)
at com.actionbarsherlock.app.SherlockFragmentActivity.onRestoreInstanceState(SherlockFragmentActivity.java:133)
at android.app.Activity.performRestoreInstanceState(Activity.java:910)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1131)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2158)
... 12 more
```

When switching from portrait to landscape I get the exception:

```
Caused by: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to net.simonvt.menudrawer.DraggableDrawer$SavedState
at net.simonvt.menudrawer.DraggableDrawer.onRestoreInstanceState(DraggableDrawer.java:622)
at android.view.View.dispatchRestoreInstanceState(View.java:12088)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2582)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2588)
at android.view.View.restoreHierarchyState(View.java:12066)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1634)
at android.app.Activity.onRestoreInstanceState(Activity.java:938)
at com.actionbarsherlock.app.SherlockFragmentActivity.onRestoreInstanceState(SherlockFragmentActivity.java:133)
at android.app.Activity.performRestoreInstanceState(Activity.java:910)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1131)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2158)
... 11 more
```

Maybe what I am trying to do is just not supported yet ?

**Comment by SimonVT** [comment]
Yeah, this isn't supported at the moment. I'll see if I can come up with a good approach for how to handle this.

**Comment by pommedeterresautee** [comment]
Hi,

I have exactly the same error in my application.

Is there a dirty workaround available now, until you find a beautiful solution?
As the issue is a saved state, is there a way to reset it to be like I am launching the application in the new state (portrait or landscape)? I don't use onRestore in my activity and I see the issue is there.

I just removed all the code I used in my application to manage the landscape (which disables the code menu drawer and replace it by a classical listview) because I believed the update would implement a working version of the landscape mode (static mode).

Anyway thank you for the library.

Regards

**Comment by SimonVT** [comment]
Can you check if the changes I pushed to the dev branch solves this?

**Comment by pommedeterresautee** [comment]
Thank you for your rapidity !

It is working great on my application.

**Comment by pommedeterresautee** [comment]
I noticed a little bug.

When I launch the app in landscape (with the statically opened menudrawer) or if I rotate, the little triangle to show the selected item in the meny doesn't appear. 

This is my init:

``` java
  private void initializeSidebar(Bundle inState) {
        if (inState != null) {
            mActivePosition = inState.getInt(STATE_ACTIVE_POSITION);
        }

        mMenuDrawer = MenuDrawer.attach(this, MenuDrawer.MENU_DRAG_CONTENT, Position.LEFT, !portrait);

        mMenuDrawer.setContentView(R.layout.main);
        List<Item> items = new ArrayList<Item>();
        for (ActionChoice current : ActionChoice.values()) {
            items.add(new Item(current.toText(), current.getIcon()));
        }
        MenuListView mList = new MenuListView(this);
        mList.setTopShadow(true);
        mAdapter = new MenuAdapter(MainActivity.this, items, mActivePosition, mMenuDrawer);
        mList.setAdapter(mAdapter);
        mList.setOnItemClickListener(mItemClickListener);
            mList.setOnScrollChangedListener(new MenuListView.OnScrollChangedListener() {
                @Override
                public void onScrollChanged() {
                    mMenuDrawer.invalidate();
                }
            });
            mMenuDrawer.setMenuView(mList);
            mMenuDrawer.setDropShadowSize(InterfaceFunctions.convertDpToPixel(4, this));
    }
```

**Comment by SimonVT** [comment]
You have to call `MenuDrawer#setActiveView(...)` for the indicator to show.

**Comment by pommedeterresautee** [comment]
Thank you! I forgot to disable another isPortrait() check I used before the library update.

I am now doing like that:

``` java
@Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View v = convertView;
        Object item = getItem(position);
        if (item instanceof Category) {
            if (v == null) {
                v = mContext.getLayoutInflater().inflate(R.layout.md__category, parent, false);
            }
            ((TextView) v).setText(((Category) item).mTitle);
        } else {
            if (v == null) {
                v = mContext.getLayoutInflater().inflate(R.layout.md__item, parent, false);
            }
            TextView tv = (TextView) v;
            ...
        }

        v.setTag(R.id.mdActiveViewPosition, position);
        if (position == mActivePosition) {
            try {
                //TODO search why it crashes here!
                mMenuDrawer.setActiveView(v, position);
            } catch (Exception e) {
                e.printStackTrace();
            }
...
    }
```

I noticed that sometimes (with the old library version of course) my users have some crashes on the setActiveView().
As it doesn't happen a lot (like one time per week) and I have several thousands of users, I thought it was not important. But now I am reworking on this part, I take the chance to tell you about it.

Unfortunately I don't find the logs... But may the way I am doing it (in getView) is a bad practice?

**Comment by SimonVT** [comment]
With ListView you have to set the active view in getView() since the view for the position can potentially change every time it's shown.
Next time it crashes, feel free to open a new issue.

**Comment by srikanthnama** [comment]
Hi.. How to set the First List Item as Default when launch the Application? when i use list.performItemClick(), i am getting errors. Pls Help me to resolve this. Thank you.
