### ISSUE TITLE
FCs on dev lib

### ISSUE THREAD

**Issue by pommedeterresautee** [SimonVT/android-menudrawer#68]
Hi,

I am using the dev branch of this library to have the static mode after a rotation. In the master version there is bug you fixed Sunday when you rotate the scree and the code switch from static to draggable drawer.

So I released a beta with that.

Few of my user are having a crash. Here is the log

``` java
java.lang.NoSuchMethodError: net.simonvt.menudrawer.MenuDrawer.postOnAnimation
at net.simonvt.menudrawer.MenuDrawer.animateIndicatorInvalidate(SourceFile:619)
at net.simonvt.menudrawer.MenuDrawer.openMenu(SourceFile:599)
                                     startAnimatingIndicator
at net.simonvt.menudrawer.MenuDrawer.openMenu(SourceFile:585)
                                     setActiveView
at com.pommedeterresautee.twoborange3.Activities.Main.MainActivity$1.onItemClick(SourceFile:132)
at android.widget.AdapterView.performItemClick(AdapterView.java:284)
at android.widget.ListView.performItemClick(ListView.java:3513)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:1881)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3835)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
at dalvik.system.NativeStart.main(Native Method) 
```

Affected devices are:
HTC Desire under 2.3.7
SGH-I747M under 4.04

Log have been retraced as I obfuscate my code.

Let me know if you want more information, I can contact these users to ask them few things.

Regards

**Comment by SimonVT** [comment]
Oh right, I moved postOnAnimation to DraggableDrawer.. Just have to move it up again.

**Comment by pommedeterresautee** [comment]
Cool!

I have tried to reproduce the bug on my side without success. How can I make a test to make my app crash now? So I will be able to test if the fix you will do is working?

Regards

Edit: "Just have to move it up again." -> have I to do something?

**Comment by SimonVT** [comment]
Just run it on 2.x and set an active view (a 2nd active view, so it
animates).

**Comment by pommedeterresautee** [comment]
Simon,

If I want to do it tonight, what should I do?

What do you mean by "Oh right, I moved postOnAnimation to DraggableDrawer.. Just have to move it up again."?

Regards

**Comment by SimonVT** [comment]
Fixed.
